tasks:
  - init: source ~/anaconda3/etc/profile.d/conda.sh && conda activate astropop && python setup.py build
  - command: source ~/anaconda3/etc/profile.d/conda.sh && conda activate astropop

image:
  file: .gitpod.Dockerfile

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: false

vscode:
  extensions:
    - aaron-bond.better-comments@2.0.5:YKNfOclR4e8XAxlj4xp2AA==
    - karyfoundation.theme-karyfoundation-themes@20.0.3:w4aePfn0e0SJgNOjXLH5iA==
    - HookyQR.beautify@1.5.0:mXo/OcopUVNHHxCPZWwlxQ==
    - lamartire.git-indicators@2.1.2:qeqMzEaDC/gSy6y3HKvG+Q==
    - Gruntfuggly.todo-tree@0.0.172:YlN69Rd0yqC/rlRPh7AHzA==
    - searKing.preview-vscode@2.1.0:QfrQf6Ej7ubvRQN81yMQkg==