name: astropop

channels:
    - astropy
    - juliotux
    - conda-forge

dependencies:
    - astropy
    - cython
    - matplotlib
    - numpy
    - sphinx-astropy
    - pytz
    - pyyaml
    - scikit-image
    - matplotlib
    - scipy
    - astroquery
    - astroscrappy
    - astroalign
    - ccdproc
    - photutils
    - sep
    - pytest-astropy
    - pip
    - ipython
    - pip:
        - sphinx-rtd-theme
        - sphinxcontrib-apidoc
        - astropy-helpers
        - pytest_check
        - sphinxcontrib-napoleon

