language: python

# We need a full clone to make sure setuptools_scm works properly
git:
    depth: false

os:
    - linux

# The apt packages below are needed for sphinx builds. A full list of packages
# that can be included can be found here:
#
# https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise

addons:
    apt:
        packages:
            - graphviz


stages:
   # Do the style check and a single test job, don't proceed if it fails
   - name: Initial tests
   # Test docs, astropy dev, and without optional dependencies
   - name: Comprehensive tests
   # These will only run when cron is opted in
   - name: Cron tests
     if: type = cron


env:
    global:

        # The following versions are the 'default' for tests, unless
        # overridden underneath. They are defined here in order to save having
        # to repeat them for all configurations.

        # The following three variables are for tox. TOXENV is a standard
        # variable that tox uses to determine the environment to run,
        # TOXARGS are arguments passed to tox, and TOXPOSARGS are arguments
        # that tox passes through to the {posargs} indicator in tox.ini.
        # The latter can be used for example to pass arguments to pytest.
        - TOXENV='test'
        - TOXARGS='-v'
        - TOXPOSARGS=''

        # The following is needed to avoid issues if e.g. Matplotlib tries
        # to open a GUI window.
        - SETUP_XVFB=True

matrix:
    # Don't wait for allowed failures
    fast_finish: true

    include:
        - os: osx
          language: c
          name: Python 3.7 with required dependencies
          stage: Cron tests
          env: PYTHON_VERSION=3.7 TOXENV=py37-test

        - os: linux
          python: 3.8
          name: Python 3.8 with required dependencies and measure coverage
          stage: Initial tests
          env: TOXENV=py38-test-cov

        - os: linux
          python: 3.8
          name: Documentation build
          stage: Comprehensive tests
          env: TOXENV=build_docs

        - os: linux
          python: 3.8
          name: Python 3.8 with developer version of astropy and numpy nightly
          stage: Comprehensive tests
          env: TOXENV=py38-test-devdeps

        - os: linux
          python: 3.7
          name: Python 3.7 with astropy 3.2 and Numpy 1.17
          stage: Comprehensive tests
          env: TOXENV=py37-test-astropy32-numpy117

        - os: linux
          python: 3.6
          name: Python 3.6 astropy LTS and Numpy 1.17
          stage: Comprehensive tests
          env: TOXENV=py36-test-astropylts-numpy117

        - os: linux
          python: 3.8
          name: Python 3.8 latest developer version of key dependencies
          stage: Cron tests
          env: TOXENV=py38-test-devdeps

        - os: linux
          python: 3.8
          name: Python 3.8 astropy 4.0 and Numpy 1.19
          stage: Comprehensive tests
          env: TOXENV=py38-test-astropy40-numpy119

    allow_failures:
        # Do a PEP8 test with flake8
        # (do allow to fail unless your code completely compliant)
        - os: linux
          python: 3.8
          name: Code style checks
          stage: Initial tests
          env: TOXENV=codestyle

before_install:
    # Create a coverage.xml for use by coveralls or codecov
    - if [[ $TOXENV == *-cov ]]; then
        export TOXPOSARGS=$TOXPOSARGS" --cov-report=xml:"$TRAVIS_BUILD_DIR"/coverage.xml";
      fi
    # # skip it for now
    # - sudo apt-get update
    # - sudo apt-get -y install astrometry.net # astrometry.net needed

install:

    # We now use the ci-helpers package to set up our Python environment
    # on Windows and MacOS X but we don't set up any other dependencies,
    # instead using tox to do this. See https://github.com/astropy/ci-helpers
    # for more information about ci-helpers.

    - if [[ $TRAVIS_OS_NAME != linux ]]; then
        git clone --depth 1 git://github.com/astropy/ci-helpers.git;
        source ci-helpers/travis/setup_conda.sh;
      fi

script:
    - pip install tox
    - tox $TOXARGS -- $TOXPOSARGS

after_success:
    # coverage deploy
    - if [[ $TOXENV == *-cov ]]; then
       pip install coveralls;
       coveralls;
       pip install codecov;
       codecov;
      fi
