# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c
cache:
  directories:
    - $HOME/.astropy/cache
    - $XDG_CACHE_HOME/astropy

os:
  - linux

stages:
  # Do the style check and a single test job, don't proceed if it fails
  - name: Initial
  # Test docs, astropy dev, and without optional dependencies
  - name: Comprehensive
    # These will only run when cron is opted in
  - name: Cron
    if: type = cron


env:
  global:
    - NAME="astropop"
    - PYTHON_VERSION=3.7
    - NUMPY_VERSION=stable
    - ASTROPY_VERSION=stable
    - EVENT_TYPE='pull_request push'
    - CONDA_ENVIRONMENT='.rtd-environment.yml'
    - MINICONDA_VERSION=latest

matrix:
  fast_finish: true

  include:
    - os: linux
      stage: Initial
      env: SETUP_CMD='egg_info'
      script: python setup.py egg_info

    - os: linux
      stage: Initial
      script: python setup.py test

    - os: linux
      stage: Initial
      env: SETUP_CMD='coverage'
      script:
        - python setup.py test --coverage
        - coveralls --rcfile='astropop/tests/coveragerc'
        - codecov
        - coverage xml; python-codacy-coverage -r coverage.xml

    - os: linux
      stage: Initial
      env: SETUP_CMD='docs'
      script: python setup.py build_docs

    - os: linux
      stage: Cron
      env: ASTROPY_VERSION=development NUMPY_VERSION=development EVENT_TYPE='cron'
      script: python setup.py test

    - os: linux
      stage: Comprehensive
      env: PYTHON_VERSION=3.7 NUMPY_VERSION=1.16 ASTROPY_VERSION=4.0 SETUP_CMD='test'
      script: python setup.py test

    - os: linux
      stage: Comprehensive
      env: PYTHON_VERSION=3.7 NUMPY_VERSION=1.14 ASTROPY_VERSION=3.2 SETUP_CMD='test'
      script: python setup.py test

    - os: linux
      stage: Comprehensive
      env: PYTHON_VERSION=3.6 NUMPY_VERSION=1.14 ASTROPY_VERSION=3.2 SETUP_CMD='test'
      script: python setup.py test

    - os: linux
      stage: Comprehensive
      env: PYTHON_VERSION=3.8 NUMPY_VERSION=1.17 ASTROPY_VERSION=4.0
      script: python setup.py test

  allow_failures:
    - os: linux
      stage: Initial
      script: flake8 astropop --count --show-source --statistics $FLAKE8_OPT

install:
  - source ./ci/travis_setup.sh
