name: "Code Style"

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: codestyle-${{ github.ref }}
  cancel-in-progress: true

jobs:
  codestyle:
    name: codestyle
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: Code Analyse
      run: tox -e codestyle

  docstyle:
    name: pydocstyle
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pydocstyle
    - name: Code Analyse
      run: pydocstyle astropop

  prospector:
    name: prospector
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install prospector pylint pyflakes bandit
    - name: Code Analyse
      run: prospector -w pyflakes -w bandit -F astropop
