name: coverage
# Run a single test to determine and upload coverage.
# Using conda to include astrometry

on:
  pull_request:
  push:
    branches: [ main ]
    tags:
  workflow_dispatch:

jobs:
  coverage:
    name: ${{ matrix.toxenv }}
    runs-on: ubuntu-latest
    if: "!(contains(github.event.head_commit.message, '[skip ci]') || contains(github.event.head_commit.message, '[ci skip]'))"
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: true
        activate-environment: ""
        auto-update-conda: true
        channels: conda-forge,defaults
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        conda install astropy numpy scipy astroquery scikit-image pytz pyyaml astroscrappy asctroalign sep reproject
    - name: Print versions
      run: |
        conda info
        conda list
    - name: Install astropop
      run: echo "$PWD"
