name: Unit Tests

on:
  pull_request:
  push:
    branches: [ master ]
    tags:
  workflow_dispatch:
  schedule:
    - cron: 11 2 * * 0

jobs:
  tests:
    name: ${{ matrix.name }} (${{ matrix.os }}, ${{ matrix.toxenv }})
    runs-on: ubuntu-latest
    if: "!(contains(github.event.head_commit.message, '[skip ci]') || contains(github.event.head_commit.message, '[ci skip]'))"
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Python 3.9 with astrometry and coverage
            python-version: 3.9
            toxenv: py39-test-numpystable-astropystable-cov-ast-cat
            coverage: true

          # - name: Python 3.10 with astrometry and coverage
          #   python-version: 3.10
          #   toxenv: py310-test-numpystable-astropystable-cov-ast-cat
          #   coverage: true

          - name: Documentation build
            python-version: 3.9
            toxenv: build_docs

          - name: Python 3.9 with devdeps and online catalogs
            python-version: 3.9
            toxenv: py39-test-devdeps-cat

          # - name: Python 3.10 with devdeps and online catalogs
          #   python-version: 3.10
          #   toxenv: py310-test-devdeps-cat

          - name: Python 3.7 with old deps and online catalogs
            python-version: 3.7
            toxenv: py37-test-astropyold-numpyold-cat

          - name: Python 3.7 with LTS deps
            python-version: 3.7
            toxenv: py37-test-astropylts-numpylts

          - name: Python 3.8 with deps
            python-version: 3.8
            toxenv: py38-test-astropylts-numpylts

          - name: Python 3.9 with stable deps
            python-version: 3.9
            toxenv: py39-test-astropystable-numpystable

          # - name: Python 3.10 with stable deps
          #   python-version: 3.10
          #   toxenv: py310-test-astropystable-numpystable

          - name: Python 3.7 with astrometry (stable)
            python-version: 3.7
            toxenv: py37-test-ast-numpystable-astropystable

          #- name: Code style checks
          #  python-version: 3.8
          #  toxenv: codestyle

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: false
        activate-environment: "astropop"
        channels: conda-forge
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python -m pip install tox-conda
    - name: Install graphviz dependency
      if: "endsWith(matrix.toxenv, 'build_docs')"
      run: sudo apt-get -y install graphviz
    - name: Run tests
      if: "! matrix.coverage"
      run: tox -v -e ${{ matrix.toxenv }}
    - name: Upload coverage to codecov
      if: "matrix.coverage"
      run: |
        tox -v -e ${{ matrix.toxenv }} -- --cov-report=xml:${{ github.workspace }}/coverage.xml
        pip install codecov
        codecov
